#!/bin/bash

unset SESSION_MANAGER

exec startxfce4 &

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
${NOVNC_DIR}/utils/launch.sh ${NOVNC_ARGS} &

#exec /etc/X11/xinit/xinitrc
